package compose

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

// WrapperName is the script Helmo keeps in <app>/.helmo for manual use. It
// runs docker compose with the same env files Helmo uses, so a plain
// "docker compose" (which does not read .helmo/env) is not needed.
const WrapperName = "dc"

const wrapperScript = `#!/bin/sh
# Generated by Helmo, overwritten on start. Use instead of "docker compose":
#   .helmo/dc up -d | ps | logs -f ...
cd "$(dirname "$0")/.." || exit 1
if [ -f .helmo/env ]; then
  if [ -f .env ]; then
    exec docker compose --env-file .env --env-file .helmo/env "$@"
  fi
  exec docker compose --env-file .helmo/env "$@"
fi
exec docker compose "$@"
`

// EnsureWrapper writes <dir>/.helmo/dc when it is missing or differs from
// the current script. The write is atomic and the file is executable.
func EnsureWrapper(dir string) error {
	helmoDir := filepath.Join(dir, ".helmo")
	path := filepath.Join(helmoDir, WrapperName)

	if cur, err := os.ReadFile(path); err == nil && bytes.Equal(cur, []byte(wrapperScript)) {
		if fi, err := os.Stat(path); err == nil && fi.Mode().Perm() == 0o755 {
			return nil
		}
	}

	tmp, err := os.CreateTemp(helmoDir, ".dc-*")
	if err != nil {
		return fmt.Errorf("write wrapper: %w", err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(wrapperScript); err != nil {
		tmp.Close()
		return fmt.Errorf("write wrapper: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("write wrapper: %w", err)
	}
	if err := os.Chmod(tmp.Name(), 0o755); err != nil {
		return fmt.Errorf("write wrapper: %w", err)
	}
	if err := os.Rename(tmp.Name(), path); err != nil {
		return fmt.Errorf("write wrapper: %w", err)
	}
	return nil
}
